# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x1a\x63om.dissertation.inventory\"&\n\x11\x43heckStockRequest\x12\x11\n\titem_name\x18\x01 \x01(\t\"2\n\rStockResponse\x12\x10\n\x08in_stock\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2z\n\x10InventoryService\x12\x66\n\nCheckStock\x12-.com.dissertation.inventory.CheckStockRequest\x1a).com.dissertation.inventory.StockResponseB8\n&com.dissertation.inventoryservice.grpcB\x0eInventoryProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.dissertation.inventoryservice.grpcB\016InventoryProto'
  _globals['_CHECKSTOCKREQUEST']._serialized_start=47
  _globals['_CHECKSTOCKREQUEST']._serialized_end=85
  _globals['_STOCKRESPONSE']._serialized_start=87
  _globals['_STOCKRESPONSE']._serialized_end=137
  _globals['_INVENTORYSERVICE']._serialized_start=139
  _globals['_INVENTORYSERVICE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
